// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "YouTube",
    defaultLocalization: "en",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .library(
            name: "ExampleKit",
            targets: ["ExampleKit"]
        ),
        .iOSApplication(
            name: "YouTube",
            targets: ["AppModule"],
            bundleIdentifier: "com.alemohamad.YouTube",
            teamIdentifier: "YOUR-TEAM-IDENTIFIER",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education,
            additionalInfoPlistContentFilePath: "AppInfo.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                "ExampleKit"
            ]
        ),
        .target(
            name: "ExampleKit"
        ),
        .testTarget(
            name: "AppModuleTest",
            dependencies: [
                "ExampleKit"
            ]
        )
    ]
)
